name        : python-pycurl
version     : 7.19.0
release     : 5
source      :
    - http://pycurl.sourceforge.net/download/pycurl-7.19.0.tar.gz : eb782dfcc5a7c023539a077462b83c167e178128ee9f7201665b9fbb1a8b0642
license     :
    - MIT
summary     : Curl module for python
builddeps   :
    - pkgconfig(python-2.7)
    - pkgconfig(libcurl)
description : |
    Easy access to libcurl from Python
setup      : |
    %patch -p1 < $pkgfiles/force_openssl.patch
    %patch -p1 < $pkgfiles/no_static_link.patch
install    : |
    python setup.py install --root="$installdir" --no-compile -O0
    mv $installdir/usr/share/doc/pycurl $installdir/usr/share/doc/python-pycurl
