name       : python-pycurl
version    : 7.43.0.3
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/p/pycurl/pycurl-7.43.0.3.tar.gz : 6f08330c5cf79fa8ef68b9912b9901db7ffd34b63e225dce74db56bb21deda8e
license    : MIT
component  : system.base
summary    : Curl module for python
description: |
    Easy access to libcurl from Python
builddeps  :
    - pkgconfig(libcurl)
    - pyflakes
    - python-bottle
    - python-flaky
    - python-nose
    - python-setuptools
setup      : |
    # remove bundled libraries
    rm -f tests/fake-curl/libcurl/*.so

    # remove test-cases that won't work in our sandbox
    rm -f tests/{ftp_test.py,seek_cb_test.py,ssh_key_cb_test.py}

    # We don't have nose-show-skipped in the repo
    sed -e 's/ --show-skipped//' -i tests/run.sh
build      : |
    %python_setup --with-openssl
install    : |
    %python_install --with-openssl
    mv $installdir/usr/share/doc/pycurl $installdir/usr/share/doc/python-pycurl
check      : |
    export PYCURL_SSL_LIBRARY=openssl
    %python_test %make test NOSETESTS="nosetests-%python2_version% -v"
