name       : python-pycurl
version    : 7.43.0.3
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/p/pycurl/pycurl-7.43.0.3.tar.gz : 6f08330c5cf79fa8ef68b9912b9901db7ffd34b63e225dce74db56bb21deda8e
homepage   : http://pycurl.io/
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming.python
summary    : Curl module for python
description: |
    PycURL is a Python interface to libcurl. PycURL can be used to fetch objects identified by a URL from a Python program, similar to the urllib Python module. PycURL is mature, very fast, and supports a lot of features.
ccache     : no
networking : yes # Tests for examples/tests/test_xmlrpc.py
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(python3)
    - pyflakes
    - python-bottle
    - python-flaky
    - python-nose
    - python-pytest
    - python-setuptools
    - python2-pyflakes
setup      : |
    %patch -p1 < $pkgfiles/skip-incompatible-libcurl-tests.patch

    # remove bundled libraries
    rm -f tests/fake-curl/libcurl/*.so

    # remove test-cases that won't work in our sandbox
    rm -f tests/{ftp_test.py,seek_cb_test.py,ssh_key_cb_test.py}

    # We don't have nose-show-skipped in the repo
    sed -e 's/ --show-skipped//' -i tests/run.sh
build      : |
    %python3_setup --with-openssl
install    : |
    %python3_install --with-openssl
    mv $installdir/usr/share/doc/pycurl $installdir/usr/share/doc/python-pycurl
#check      : |
#    export PYCURL_SSL_LIBRARY=openssl
#    rm examples/tests/{test_gtk.py,test_build_config.py}
#    %python3_test pytest3 -v -k "not (test_getinfo or test_libcurl_ssl)"
