name       : python-pycurl
version    : 7.43.0.2
release    : 6
source     :
    - https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz : 0f0cdfc7a92d4f2a5c44226162434e34f7d6967d3af416a6f1448649c09a25a4
license    :
    - MIT
component  : system.base
summary    : Curl module for python
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(libcurl)
description: |
    Easy access to libcurl from Python
setup      : |
    # %patch -p1 < $pkgfiles/force_openssl.patch
    # %patch -p1 < $pkgfiles/no_static_link.patch
    %python_setup --with-openssl
install    : |
    %python_install --with-openssl
    mv $installdir/usr/share/doc/pycurl $installdir/usr/share/doc/python-pycurl
