name       : python-pycurl
version    : 7.43.0.3
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/p/pycurl/pycurl-7.43.0.3.tar.gz : 6f08330c5cf79fa8ef68b9912b9901db7ffd34b63e225dce74db56bb21deda8e
homepage   : http://pycurl.io/
license    : MIT
component  : system.base
summary    : Curl module for python
description: |
    PycURL is a Python interface to libcurl. PycURL can be used to fetch objects identified by a URL from a Python program, similar to the urllib Python module. PycURL is mature, very fast, and supports a lot of features
builddeps  :
    - pkgconfig(libcurl)
    - python-setuptools
build      : |
    %python_setup --with-openssl
install    : |
    %python_install --with-openssl
    mv $installdir/usr/share/doc/pycurl $installdir/usr/share/doc/python-pycurl
