name       : python-pycurl
version    : 7.43.0.2
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/p/pycurl/pycurl-7.43.0.2.tar.gz : 0f0cdfc7a92d4f2a5c44226162434e34f7d6967d3af416a6f1448649c09a25a4
license    : MIT
component  : system.base
summary    : Curl module for python
description: |
    Easy access to libcurl from Python
builddeps  :
    - pkgconfig(libcurl)
    - pyflakes
    - python-bottle
    - python-flaky
    - python-nose
    - python-setuptools
setup      : |
    # remove bundled libraries
    rm -f tests/fake-curl/libcurl/*.so

    # remove test-cases that won't work in our sandbox
    rm -f tests/{ftp_test.py,seek_cb_test.py,ssh_key_cb_test.py}

    # We don't have nose-show-skipped in the repo
    sed -e 's/ --show-skipped//' -i tests/run.sh
build      : |
    %python_setup --with-openssl
install    : |
    %python_install --with-openssl
    mv $installdir/usr/share/doc/pycurl $installdir/usr/share/doc/python-pycurl
check     : |
    export PYCURL_SSL_LIBRARY=openssl
    %python_test %make test NOSETESTS="nosetests-%python2_version% -v"
